export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_PROFILE_POSTS_SUCCESS = 'LOAD_PROFILE_POSTS_SUCCESS';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const LIKE_UNLIKE_POST_SUCCESS = 'LIKE_UNLIKE_POST_SUCCESS';
